version: '3'
services:
  node:
    container_name: davesolancesmith
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"