version: '3.7'
services:
  node:
    container_name: davesolancesmith
    build: .
    command: ["npm", "run", "start"]
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"